import { NextResponse } from "next/server";
import { getProductById } from "@/lib/mock-data";

export const runtime = "nodejs";

export async function GET(
  _request: Request,
  { params }: { params: Promise<{ productId: string }> },
) {
  const { productId } = await params;
  const product = getProductById(productId);

  if (!product) {
    return new NextResponse("Product not found", { status: 404 });
  }

  const contents = [
    `Product: ${product.name}`,
    `Category: ${product.category}`,
    "",
    "Your download was generated by the demo storefront.",
    "Replace this route with a real signed file URL or secure storage download.",
  ].join("\n");

  return new NextResponse(contents, {
    headers: {
      "Content-Type": "application/octet-stream",
      "Content-Disposition": `attachment; filename=\"${product.slug}.txt\"`,
      "Cache-Control": "no-store",
    },
  });
}
